import { check, int, mysqlEnum, mysqlTable, text, timestamp, varchar, uniqueIndex, index } from "drizzle-orm/mysql-core";
import { sql } from "drizzle-orm";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const escolas = mysqlTable("escolas", {
  id: int("id").autoincrement().primaryKey(), nome: varchar("nome", { length: 180 }).notNull(), codigo: varchar("codigo", { length: 30 }).notNull().unique(), ativo: int("ativo").default(1).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export const usuarios = mysqlTable("usuarios", {
  id: int("id").autoincrement().primaryKey(), authUserId: int("authUserId").notNull().references(() => users.id), nome: varchar("nome", { length: 180 }).notNull(), email: varchar("email", { length: 320 }).notNull(), perfil: mysqlEnum("perfil", ["ADMIN", "ESCOLA"]).notNull(), escolaId: int("escolaId").references(() => escolas.id), ativo: int("ativo").default(1).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => ({ authUserUnique: uniqueIndex("usuarios_auth_user_unique").on(table.authUserId), escolaIndex: index("usuarios_escola_idx").on(table.escolaId), roleSchoolCheck: check("usuarios_perfil_escola_check", sql`perfil = 'ADMIN' OR escolaId IS NOT NULL`) }));
export const alunos = mysqlTable("alunos", {
  id: int("id").autoincrement().primaryKey(), escolaId: int("escolaId").notNull().references(() => escolas.id), nome: varchar("nome", { length: 220 }).notNull(), inep: varchar("inep", { length: 30 }), turma: varchar("turma", { length: 100 }).notNull(), matricula: varchar("matricula", { length: 50 }).notNull(), dataMatricula: varchar("dataMatricula", { length: 10 }), filiacao1: varchar("filiacao1", { length: 220 }), filiacao2: varchar("filiacao2", { length: 220 }), responsavel: varchar("responsavel", { length: 220 }), fone1: varchar("fone1", { length: 30 }), fone2: varchar("fone2", { length: 30 }), endereco: text("endereco"), ativo: int("ativo").default(1).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => ({ escolaMatriculaUnique: uniqueIndex("alunos_escola_matricula_unique").on(table.escolaId, table.matricula), escolaInepUnique: uniqueIndex("alunos_escola_inep_unique").on(table.escolaId, table.inep), escolaIndex: index("alunos_escola_idx").on(table.escolaId), turmaIndex: index("alunos_turma_idx").on(table.turma), nomeIndex: index("alunos_nome_idx").on(table.nome), matriculaIndex: index("alunos_matricula_idx").on(table.matricula) }));
export const faltas = mysqlTable("faltas", {
  id: int("id").autoincrement().primaryKey(), alunoId: int("alunoId").notNull().references(() => alunos.id), escolaId: int("escolaId").notNull().references(() => escolas.id), dataFalta: varchar("dataFalta", { length: 10 }).notNull(), quantidadeDias: int("quantidadeDias").notNull(), motivo: varchar("motivo", { length: 160 }).notNull(), observacao: text("observacao"), ficaiParticipa: mysqlEnum("ficaiParticipa", ["SIM", "NAO"]).default("NAO").notNull(), envioId: int("envioId"), registradoPor: int("registradoPor").notNull().references(() => usuarios.id), status: mysqlEnum("status", ["RASCUNHO", "ENVIADO", "EM_ANALISE", "APROVADO", "REJEITADO"]).default("RASCUNHO").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => ({ alunoIndex: index("faltas_aluno_idx").on(table.alunoId), escolaIndex: index("faltas_escola_idx").on(table.escolaId), dataIndex: index("faltas_data_idx").on(table.dataFalta) }));
export const enviosFaltas = mysqlTable("envios_faltas", {
  id: int("id").autoincrement().primaryKey(), escolaId: int("escolaId").notNull().references(() => escolas.id), usuarioId: int("usuarioId").notNull().references(() => usuarios.id), periodo: varchar("periodo", { length: 80 }).notNull(), observacao: text("observacao"), status: mysqlEnum("status", ["RASCUNHO", "ENVIADO", "EM_ANALISE", "APROVADO", "REJEITADO"]).default("RASCUNHO").notNull(), enviadoEm: timestamp("enviadoEm"), analisadoEm: timestamp("analisadoEm"), analisadoPor: int("analisadoPor").references(() => usuarios.id), observacaoAdmin: text("observacaoAdmin"), createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => ({ escolaIndex: index("envios_escola_idx").on(table.escolaId), statusIndex: index("envios_status_idx").on(table.status) }));
export const importacoesPdf = mysqlTable("importacoes_pdf", {
  id: int("id").autoincrement().primaryKey(), escolaId: int("escolaId").references(() => escolas.id), usuarioId: int("usuarioId").notNull().references(() => usuarios.id), nomeArquivo: varchar("nomeArquivo", { length: 255 }).notNull(), totalPaginas: int("totalPaginas").default(0).notNull(), totalAlunos: int("totalAlunos").default(0).notNull(), status: varchar("status", { length: 40 }).notNull(), erros: text("erros"), avisos: text("avisos"), createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => ({ escolaIndex: index("importacoes_escola_idx").on(table.escolaId) }));

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Escola = typeof escolas.$inferSelect; export type Aluno = typeof alunos.$inferSelect; export type Falta = typeof faltas.$inferSelect; export type EnvioFalta = typeof enviosFaltas.$inferSelect;
