import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { confirmStudentImport, createAbsence, createBusinessUser, createImportLog, createSchool, createSubmission, getBusinessUser, normalizePeriod, getOverview, getSchoolByName, listAbsences, listBusinessUsers, listSchools, listStudents, listSubmissions, reviewSubmission, updateSchool, updateStudent } from "./db";

const adminProcedure = protectedProcedure.use(({ ctx, next }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Acesso exclusivo do administrador." }); return next(); });
const businessContext = async (userId: number, authRole: string) => { const businessUser = await getBusinessUser(userId); if (authRole === "admin") return { perfil: "ADMIN" as const, escolaId: undefined }; if (!businessUser || businessUser.perfil !== "ESCOLA" || !businessUser.escolaId || !businessUser.ativo) throw new TRPCError({ code: "FORBIDDEN", message: "Usuário sem unidade escolar ativa vinculada." }); return { perfil: "ESCOLA" as const, escolaId: businessUser.escolaId }; };
const statusSchema = z.enum(["RASCUNHO", "ENVIADO", "EM_ANALISE", "APROVADO", "REJEITADO"]); const periodSchema = z.string().regex(/^(20\d{2}-(0[1-9]|1[0-2])|(janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro) de 20\d{2})$/i, "Informe o período como YYYY-MM ou Mês de YYYY.");

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  dashboard: router({ overview: protectedProcedure.query(({ ctx }) => businessContext(ctx.user.id, ctx.user.role).then(scope => getOverview(scope.escolaId))) }),
  schools: router({ list: adminProcedure.query(() => listSchools()), create: adminProcedure.input(z.object({ nome: z.string().min(3).max(180), codigo: z.string().min(1).max(30) })).mutation(({ input }) => createSchool(input)), update: adminProcedure.input(z.object({ id: z.number().int().positive(), nome: z.string().min(3).max(180), codigo: z.string().min(1).max(30), ativo: z.number().int().min(0).max(1).optional() })).mutation(({ input }) => updateSchool(input)) }),
  students: router({ list: protectedProcedure.input(z.object({ escolaId: z.number().optional() }).optional()).query(async ({ ctx, input }) => { const scope = await businessContext(ctx.user.id, ctx.user.role); if (scope.perfil === "ESCOLA" && input?.escolaId && input.escolaId !== scope.escolaId) throw new TRPCError({ code: "FORBIDDEN", message: "Acesso restrito à escola vinculada." }); return listStudents(scope.escolaId ?? input?.escolaId); }), update: protectedProcedure.input(z.object({ id: z.number().int().positive(), nome: z.string().min(2).max(220), turma: z.string().min(1).max(100), responsavel: z.string().optional(), fone1: z.string().optional(), fone2: z.string().optional(), endereco: z.string().optional(), escolaId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const scope = await businessContext(ctx.user.id, ctx.user.role); if (scope.perfil === "ESCOLA" && input.escolaId !== scope.escolaId) throw new TRPCError({ code: "FORBIDDEN", message: "Acesso restrito à escola vinculada." }); return updateStudent(input); }) }),
  absences: router({ list: protectedProcedure.input(z.object({ escolaId: z.number().optional(), alunoId: z.number().int().positive().optional(), status: statusSchema.optional(), ficaiParticipa: z.enum(["SIM", "NAO"]).optional(), search: z.string().optional(), period: z.string().optional(), turma: z.string().optional() }).optional()).query(async ({ ctx, input }) => { const scope = await businessContext(ctx.user.id, ctx.user.role); if (scope.perfil === "ESCOLA" && input?.escolaId && input.escolaId !== scope.escolaId) throw new TRPCError({ code: "FORBIDDEN", message: "Acesso restrito à escola vinculada." }); return listAbsences({ ...input, escolaId: scope.escolaId ?? input?.escolaId }); }), create: protectedProcedure.input(z.object({ alunoId: z.number().int().positive(), escolaId: z.number().int().positive(), dataFalta: z.string().min(1), quantidadeDias: z.number().int().positive(), motivo: z.string().min(1).max(160), observacao: z.string().optional(), ficaiParticipa: z.enum(["SIM", "NAO"]).default("NAO") })).mutation(async ({ ctx, input }) => { const scope = await businessContext(ctx.user.id, ctx.user.role); if (scope.perfil === "ESCOLA" && input.escolaId !== scope.escolaId) throw new TRPCError({ code: "FORBIDDEN", message: "Acesso restrito à escola vinculada." }); const businessUser = await getBusinessUser(ctx.user.id); if (!businessUser) throw new TRPCError({ code: "FORBIDDEN", message: "Usuário sem perfil operacional." }); return createAbsence({ ...input, registradoPor: businessUser.id }); }) }),
  submissions: router({ list: protectedProcedure.query(async ({ ctx }) => { const scope = await businessContext(ctx.user.id, ctx.user.role); return listSubmissions(scope.escolaId); }), statuses: protectedProcedure.query(() => statusSchema.options), create: protectedProcedure.input(z.object({ escolaId: z.number().int().positive().optional(), periodo: periodSchema, observacao: z.string().optional() })).mutation(async ({ ctx, input }) => { const scope = await businessContext(ctx.user.id, ctx.user.role); if (scope.perfil === "ESCOLA" && input.escolaId && input.escolaId !== scope.escolaId) throw new TRPCError({ code: "FORBIDDEN", message: "Acesso restrito à escola vinculada." }); const escolaId = scope.escolaId ?? input.escolaId; if (!escolaId) throw new TRPCError({ code: "BAD_REQUEST", message: "Informe a escola do envio." }); const businessUser = await getBusinessUser(ctx.user.id); if (!businessUser) throw new TRPCError({ code: "FORBIDDEN", message: "Usuário sem perfil operacional." }); const periodo = normalizePeriod(input.periodo); if (!periodo) throw new TRPCError({ code: "BAD_REQUEST", message: "Informe um período válido." }); return createSubmission({ escolaId, periodo, observacao: input.observacao, usuarioId: businessUser.id }, (ctx as any).database); }), review: adminProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["APROVADO", "REJEITADO", "EM_ANALISE"]), observacaoAdmin: z.string().optional() })).mutation(async ({ ctx, input }) => { const businessUser = await getBusinessUser(ctx.user.id); return reviewSubmission({ ...input, analisadoPor: businessUser?.id ?? ctx.user.id }); }) }),
  users: router({ list: adminProcedure.query(() => listBusinessUsers()), create: adminProcedure.input(z.object({ authUserId: z.number().int().positive(), nome: z.string().min(2).max(180), email: z.string().email(), perfil: z.enum(["ADMIN", "ESCOLA"]), escolaId: z.number().int().positive().optional() })).mutation(({ input }) => { if (input.perfil === "ESCOLA" && !input.escolaId) throw new TRPCError({ code: "BAD_REQUEST", message: "Perfil ESCOLA exige uma unidade vinculada." }); return createBusinessUser(input); }) }),
  imports: router({ log: adminProcedure.input(z.object({ escolaId: z.number().int().positive().optional(), usuarioId: z.number().int().positive(), nomeArquivo: z.string().min(1), totalPaginas: z.number().int().nonnegative(), totalAlunos: z.number().int().nonnegative(), status: z.string().min(1), erros: z.string().optional(), avisos: z.string().optional() })).mutation(({ input }) => createImportLog(input)), confirm: adminProcedure.input(z.object({ escola: z.string().min(1), students: z.array(z.object({ nome: z.string(), inep: z.string().optional(), turma: z.string(), matricula: z.string(), dataMatricula: z.string().optional(), filiacao1: z.string().optional(), filiacao2: z.string().optional(), responsavel: z.string().optional(), fone1: z.string().optional(), fone2: z.string().optional(), endereco: z.string().optional() })) })).mutation(async ({ input }) => { const school = await getSchoolByName(input.escola); if (!school) throw new TRPCError({ code: "BAD_REQUEST", message: "Escola identificada no PDF não está cadastrada." }); return confirmStudentImport({ escolaId: school.id, students: input.students }); }) }),
});
export type AppRouter = typeof appRouter;
